# render.yaml

services:
  - type: web
    name: hoa-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: YOUR_NEON_DB_URL  # Set actual value in Render UI
